### ISSUE TITLE
Recommended workflows!

### ISSUE THREAD

**Issue by toyxyz** [tukisuwa/tksw_node#2]
Here's a workflow for processing a large number of images in ComfyUI. 

Using the Queue Trigger in the Impack pack, you can set total to the number of images and then connect count to the Manual index to run the workflow as many times as you want. 

![image](https://github.com/user-attachments/assets/1fdc4ece-20ba-4e37-96bf-90a94eb1f622)

**Comment by tukisuwa** [comment]
なるほど、いい方法ですね！
確かに今のままだと処理回数の上限が設定できませんからね。
……時間が出来たらそのためのノードも作ってみようかな？
